apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-inference-canary
  namespace: aurora-system
  labels:
    app: aurora-inference
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurora-inference
      track: canary
  template:
    metadata:
      labels:
        app: aurora-inference
        track: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: aurora-sa
      containers:
      - name: inference
        image: aayud/aurora-inference:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: API_KEY
          value: "aurora-internal-key"
        - name: MODEL_NAME
          value: "california-housing"
        - name: MODEL_ALIAS
          value: "canary"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-server.aurora-system.svc.cluster.local:5000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aurora-s3-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aurora-s3-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://rook-ceph-rgw-mlflow-store.rook-ceph.svc.cluster.local:80
        - name: AWS_S3_FORCE_PATH_STYLE
          value: "true"
        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: aurora-inference-canary
  namespace: aurora-system
spec:
  selector:
    app: aurora-inference
    track: canary
  ports:
  - port: 80
    targetPort: 8000
